# depends: spanfill_lite, nn1
#' Estimate Hole Index for Each Observed Output Point
#'
#' This function computes the "hole index" (hi) for each observed output point,
#' which measures how much of a "hole" or "gap" exists in the output space near
#' that point. Points with high hi values are in regions with large unfilled gaps,
#' while points with low hi values are in well-covered regions.
#'
#' The hole index is the key driver of the OSFD acquisition function: we want to
#' select new input points whose predicted outputs will fill the largest holes.
#'
#' @param Y_scaled Matrix (n x q): scaled output points in [0, 1]^q (from osfd_scale_Y)
#'
#' @return Numeric vector of length n: hole index hi[i] for each row i of Y_scaled.
#'   Higher values indicate larger holes. Some values may be NA if the point has
#'   no nearby gaps to measure.
#'
#' @details
#' Algorithm:
#'   1. Generate a set A of "candidate" points that fill the output space
#'      (using spanfill_lite, which generates points in regions with few observations)
#'
#'   2. For each candidate point in A, find its nearest neighbor among the
#'      observed outputs Y_scaled, and record the distance
#'
#'   3. For each observed output point Y_scaled[i, ], find the maximum distance
#'      among all candidate points whose nearest neighbor is Y_scaled[i, ]
#'
#'   4. This maximum distance is hi[i] - it measures the size of the largest
#'      hole that Y_scaled[i, ] is responsible for covering
#'
#' Intuition:
#'   - If Y_scaled[i, ] is the nearest neighbor to many distant candidate points,
#'     it means there are large unfilled regions near Y_scaled[i, ], so hi[i] is large
#'   - If all candidate points near Y_scaled[i, ] are close, the region is well-filled,
#'     so hi[i] is small
#'
#' Technical notes:
#'   - The set A is generated by spanfill_lite, which uses a geometric algorithm
#'     to find regions of the output space that are poorly covered
#'   - The nearest neighbor search is performed by nn1 (fast C++ implementation)
#'   - If min(idx) == 0, we add 1 because some NN implementations use 0-indexing
#'
#' @export
estimate_hi_from_outputs <- function(Y_scaled) {

  # Note: The variable k = 7 was originally used for PCA dimensionality reduction
  # (see commented code below), but we now work directly with the full Y_scaled.
  # The variable k is kept for historical compatibility but is currently unused.
  k <- 7

  # Original code used PCA to reduce dimensionality before hole estimation:
  # pc <- prcomp(Y_scaled, center = TRUE, scale. = FALSE)
  # Yp <- pc$x[, 1:k, drop = FALSE]
  # This could be useful for very high-dimensional outputs, but we found that
  # working in the full output space gives better results.

  # Use the full scaled output space (no dimensionality reduction)
  Yp <- Y_scaled

  # Print progress message (useful for monitoring long-running experiments)
  print("About to calculate the 'hole distance' in the observed outputs.")

  # --------------------------------------------------------------------------
  # Step 1: Generate candidate points in regions with large holes
  # --------------------------------------------------------------------------
  # spanfill_lite returns a set A of candidate points that are positioned to
  # fill gaps in the observed outputs. These are not actual output points, but
  # synthetic points that represent where we would like to have observations.
  A <- spanfill_lite(Yp)

  # Print dimensions for diagnostics
  cat(sprintf(
    "m=%d |A|=%d q=%d \n",
    nrow(Y_scaled),  # number of observed outputs
    nrow(A),         # number of candidate hole-filling points generated
    ncol(Y_scaled)   # output dimension
  ))

  # --------------------------------------------------------------------------
  # Step 2: Find nearest neighbor in Yp for each candidate point in A
  # --------------------------------------------------------------------------
  # For each point in A, find which observed output point in Yp is closest.
  # nn$idx[i] = index of nearest neighbor in Yp for candidate point A[i, ]
  # nn$dist[i] = distance from A[i, ] to its nearest neighbor
  nn <- nn1(data = Yp, query = A)

  # Extract nearest neighbor indices and distances
  idx <- nn$idx
  dist <- nn$dist

  # Handle 0-based indexing if present (some NN implementations use 0-indexing)
  if (min(idx, na.rm = TRUE) == 0) {
    idx <- idx + 1L  # Convert to 1-based indexing for R
  }

  # --------------------------------------------------------------------------
  # Step 3: Compute hole index for each observed output point
  # --------------------------------------------------------------------------
  # For each observed output point Yp[i, ], we want to know:
  # "What is the maximum distance to any candidate point that has me as its
  #  nearest neighbor?"
  # This maximum distance is the hole index hi[i].

  m <- nrow(Yp)  # number of observed outputs

  # Initialize hole index vector (all NA initially)
  hi <- rep(NA_real_, m)

  # For each unique nearest neighbor index, find the maximum distance
  # tapply groups dist by idx and computes max for each group
  mx <- tapply(dist, idx, max, na.rm = TRUE)

  # Assign the maximum distances to the corresponding observed points
  # names(mx) are the observed point indices (as characters)
  # mx values are the maximum hole distances for those points
  hi[as.integer(names(mx))] <- as.numeric(mx)

  # Return the hole index vector
  # Points with NA have no candidate points assigned to them (rare)
  return(hi)

  # Alternative implementation using data.table (commented out but functionally equivalent):
  # hi_by <- dt[, .(mx = max(dist, na.rm = TRUE)), by = idx]
  # hi <- numeric(length = m)
  # hi[hi_by$idx] <- hi_by$mx
  # return(hi)
}
