# depends: 
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eoe_omp_set_threads <- function(n) {
    invisible(.Call(`_epiOutputExpansion_eoe_omp_set_threads`, n))
}

eoe_omp_max_threads <- function() {
    .Call(`_epiOutputExpansion_eoe_omp_max_threads`)
}

eoe_omp_threads_in_parallel <- function() {
    .Call(`_epiOutputExpansion_eoe_omp_threads_in_parallel`)
}

scale_cpp <- function(M) {
    .Call(`_epiOutputExpansion_scale_cpp`, M)
}

knnx_my <- function(data, points, k) {
    .Call(`_epiOutputExpansion_knnx_my`, data, points, k)
}

knn_my <- function(data, k) {
    .Call(`_epiOutputExpansion_knn_my`, data, k)
}

runif_in_sphere_cpp <- function(n, p) {
    .Call(`_epiOutputExpansion_runif_in_sphere_cpp`, n, p)
}

ball_gen <- function(cen, rad, n, p = 0L, sub_ = NULL, rand = TRUE, twinsample_ = NULL) {
    .Call(`_epiOutputExpansion_ball_gen`, cen, rad, n, p, sub_, rand, twinsample_)
}

approx_gen <- function(X, d, p, rand = TRUE, twinsample_ = NULL) {
    .Call(`_epiOutputExpansion_approx_gen`, X, d, p, rand, twinsample_)
}

filldist_cpp <- function(M, p, rand = TRUE, twinsample_ = NULL) {
    .Call(`_epiOutputExpansion_filldist_cpp`, M, p, rand, twinsample_)
}

perturb_cpp <- function(D, filldist, q, CAND_ = NULL, cri = "EI", balance_ratio = 0.5, rand = TRUE, twinsample_ = NULL) {
    .Call(`_epiOutputExpansion_perturb_cpp`, D, filldist, q, CAND_, cri, balance_ratio, rand, twinsample_)
}

